# Generated by Django 5.2 on 2025-04-06 15:29

# Django
import django.db.models.deletion
from django.db import migrations, models

# Django Simple Catalog
import django_simple_catalog.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_simple_catalog",
            "0003_product_active_alter_product_short_description",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="django_simple_catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to=django_simple_catalog.models.product_image_upload_to
            ),
        ),
    ]
