# Generated by Django 5.2 on 2025-04-06 18:42

# Django
from django.db import migrations, models

# Django Simple Catalog
import django_simple_catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_simple_catalog", "0004_alter_product_category_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=django_simple_catalog.models.product_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Limited to 120 characters",
                max_length=120,
                null=True,
            ),
        ),
    ]
